packages:
  - block
  - kind
  - model
  - software/vdj-region-tools
  - test
  - ui
  - workflow
catalog:
  "@milaboratories/graph-maker": 1.4.8
  "@milaboratories/helpers": 1.14.5
  "@platforma-open/milaboratories.software-repseqio": ^2.5.0-13-master
  "@platforma-open/milaboratories.runenv-python-3": 1.8.2
  ag-grid-enterprise: ~34.1.2
  ag-grid-vue3: ~34.1.2
  "@platforma-open/milaboratories.software-mitool": 2.3.1-140-main
  "@platforma-sdk/model": 1.82.0
  "@platforma-sdk/ui-vue": 1.82.1
  "@platforma-sdk/workflow-tengo": 6.8.2
  "@platforma-sdk/test": 1.82.4
  "@platforma-sdk/block-kind": 1.1.0
  "@platforma-sdk/block-tools": 2.14.3
  "@platforma-sdk/tengo-builder": 4.0.23
  "@platforma-sdk/package-builder": 3.15.0
  "@milaboratories/ts-builder": 1.7.0
  "@milaboratories/ts-configs": 1.4.0
  typescript: ~5.6.3
  turbo: ~2.8.11
  shx: ~0.4.0
  "@changesets/cli": ~2.29.8
  vitest: ~4.0.18
  vue: 3.5.24
