packages:
  - block
  - model
  - test
  - ui
  - workflow
catalog:
  "@milaboratories/helpers": 1.14.2
  ag-grid-enterprise: ~34.1.2
  ag-grid-vue3: ~34.1.2
  "@platforma-open/milaboratories.software-mitool": 2.3.1-52-main
  "@platforma-sdk/model": 1.79.14
  "@platforma-sdk/ui-vue": 1.79.14
  "@platforma-sdk/workflow-tengo": 6.6.3
  "@platforma-sdk/test": 1.79.14
  "@platforma-sdk/block-tools": 2.11.0
  "@platforma-sdk/tengo-builder": 4.0.8
  "@platforma-sdk/package-builder": 3.13.0
  "@milaboratories/ts-builder": 1.5.2
  "@milaboratories/ts-configs": 1.2.3
  turbo: ~2.8.11
  shx: ~0.4.0
  "@changesets/cli": ~2.29.8
  vitest: ~4.0.18
  vue: 3.5.24
